//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPepak
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DigitalPepakEntities1 : DbContext
    {
        public DigitalPepakEntities1()
            : base("name=DigitalPepakEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DetailKui> DetailKuis { get; set; }
        public DbSet<Hanacaraka> Hanacarakas { get; set; }
        public DbSet<Kategori> Kategoris { get; set; }
        public DbSet<KawruhBasa> KawruhBasas { get; set; }
        public DbSet<Kewan> Kewans { get; set; }
        public DbSet<Kui> Kuis { get; set; }
        public DbSet<Paramasastra> Paramasastras { get; set; }
        public DbSet<Paribasan> Paribasans { get; set; }
        public DbSet<Parikan> Parikans { get; set; }
        public DbSet<Soal> Soals { get; set; }
        public DbSet<UserDigipak> UserDigipaks { get; set; }
        public DbSet<Wayang> Wayangs { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GetNewDetailKuisId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewDetailKuisId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewHanacarakaId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewHanacarakaId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewKawruhBasaId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewKawruhBasaId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewKewanId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewKewanId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewKuisId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewKuisId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewParamasastraId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewParamasastraId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewParibasanId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewParibasanId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewParikanId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewParikanId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewSoalId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewSoalId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewUserId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewUserId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewWayangId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewWayangId");
        }
    }
}
