//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPepak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public Kategori()
        {
            this.Hanacarakas = new HashSet<Hanacaraka>();
            this.KawruhBasas = new HashSet<KawruhBasa>();
            this.Kewans = new HashSet<Kewan>();
            this.Soals = new HashSet<Soal>();
            this.Paramasastras = new HashSet<Paramasastra>();
            this.Paribasans = new HashSet<Paribasan>();
            this.Parikans = new HashSet<Parikan>();
            this.Wayangs = new HashSet<Wayang>();
        }
    
        public int KategoriId { get; set; }
        public string Jenis { get; set; }
    
        public virtual ICollection<Hanacaraka> Hanacarakas { get; set; }
        public virtual ICollection<KawruhBasa> KawruhBasas { get; set; }
        public virtual ICollection<Kewan> Kewans { get; set; }
        public virtual ICollection<Soal> Soals { get; set; }
        public virtual ICollection<Paramasastra> Paramasastras { get; set; }
        public virtual ICollection<Paribasan> Paribasans { get; set; }
        public virtual ICollection<Parikan> Parikans { get; set; }
        public virtual ICollection<Wayang> Wayangs { get; set; }
    }
}
